### PR TITLE
Fix packaging introduced in Assimp 5.0

### PR DESCRIPTION
**Pull request by jcarpent**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jcarpent** [comment]
@wolfv Could you grant me with the maintener rights?

**Comment by wolfv** [comment]
yes for sure. looks good to me! 

btw I am working on a Gazebo build for Linux... Hopefully we have that soon :) Also just packaged the Dart physics library.

**Comment by jcarpent** [comment]
@wolfv Thanks a lot! 
Fantastic for Gazebo and Dart! 

BTW You should come one of those days to Inria to show your roadmap. It seems very impressive.

**Comment by wolfv** [comment]
@jcarpent shoot me an email @ w.vollprecht@gmail.com :)

I'll be in Saclay on Wednesday, and Paris on Tuesday if it works on such a short notice (otherwise I just moved to Berlin (still with QuantStack) but will be around from time to time).

**Pull request merged**
