### PR TITLE
Use ninja in test, detect if the sysroot librt is linked in cmake targets and fix RT linking

### PR DESCRIPTION
**Pull request by traversaro**
Let's see if with these change we are able to detected the regression in https://github.com/conda-forge/assimp-feedstock/issues/14 .

Fix https://github.com/conda-forge/assimp-feedstock/issues/32 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
No, even by using ninja the problem does not emerge for some reason.

**Comment by traversaro** [comment]
> No, even by using ninja the problem does not emerge for some reason.

I added directly a check on the `INTERFACE_LINK_LIBRARIES` value to detect if the complete librt is linked for some reason.

**Comment by traversaro** [comment]
> > No, even by using ninja the problem does not emerge for some reason.
> 
> I added directly a check on the `INTERFACE_LINK_LIBRARIES` value to detect if the complete librt is linked for some reason.

Finally this is working. At this point, I also add a fix for this.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The PR is now ready for merging, if you have any opinion on this @conda-forge/assimp feel free to comment, thanks!

**Comment by wolfv** [comment]
LGTM!

**Pull request merged**
