### PR TITLE
Fix CMake config files

### PR DESCRIPTION
**Pull request by traversaro**
Backport of https://github.com/assimp/assimp/pull/3455 to v5.0.1 . 

This should fix https://github.com/conda-forge/assimp-feedstock/issues/12 and any similar problem on the `assimp::assimp` imported target. 
 
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

This does not seems to be related to the PR. What is the best way to proceed in this case @wolfv ? Just fix it along the way?

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
There is a conflict with the patch added in https://github.com/conda-forge/assimp-feedstock/pull/8 . @Tobias-Fischer  If I am not wrong, the new patch should solve all the possible linking problems and will make the old patch not useful anymore, but to be honest I can't this. The only change that is not included in the new patch is some RPATH settings, but I guess that those one should be disable or useless in any case in conda.

**Comment by Tobias-Fischer** [comment]
Hi @traversaro,
Many thanks for the PR! You are more than welcome to remove the patch introduced in #8; we found that #8 does not improve the ability to link to assimp but in fact makes it worse. Therefore, we currently build `ros-noetic` against an old version of assimp on OSX (see https://github.com/RoboStack/ros-noetic/blob/master/conda-forge.yaml#L183).

So it would be great if you remove the old patch, and we can then rebuild ros-noetic with the new assimp version and see whether it links okay.

Many thanks again!

**Comment by traversaro** [comment]
Perfect @Tobias-Fischer, I have dropped the osx patch, thanks! Note that my patch fixes (I hope) all the uses of `assimp::assimp` imported target, but if downstream projects find assimp in some other way (pkg-config, for example) it should not affect them in any way.

**Comment by wolfv** [comment]
thanks @traversaro !

**Comment by traversaro** [comment]
Just to understand, the Travis CI failure could be ignored? By looking at the log, it seems that the compiler was running out of memory or something like that.

**Comment by wolfv** [comment]
indeed, that's a weird failure. Recently ppc64le builds have worked ok-ish... but travis has given us a lot of headaches. Usually re-running travis worked.

I think PPC64LE is also esoteric enough that we don't really care a 100% for that build.

**Comment by Tobias-Fischer** [comment]
Seems to work nicely on OSX by the way, thanks again @traversaro: https://dev.azure.com/roboforge/ros_pipelines/_build/results?buildId=781&view=logs&j=837f1829-4336-5db1-1bb2-3164775d7cf9

**Pull request merged**
