### PR TITLE
Add another patch from https://github.com/assimp/assimp/pull/2962

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)

Still on OSX one cannot link to assimp at the moment: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=208246&view=logs&jobId=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
This is just a blind test, I am not sure whether it actually solves the problem.

**Comment by Tobias-Fischer** [comment]
This could also be relevant: https://github.com/robotology/idyntree/issues/693

/cc @traverso

**Comment by Tobias-Fischer** [comment]
Hold back merging this. I now think that these patches which were recently introduced to assimp (after the release and that I pulled in in PR #8) make things worse rather than better.

This is definitely a cmake problem and people complain upstream that the packages are not relocatable (https://github.com/assimp/assimp/issues/3365 https://github.com/assimp/assimp/issues/3260 https://github.com/assimp/assimp/issues/1517).

Does anyone have good enough cmake skills to investigate the osx specific problem we encounter here? I can't even remember what the original linking issue was before merging #8 :(. Fixing this will help us building rviz in https://github.com/RoboStack/ros-noetic for OSX which would be super cool.

**Comment by traversaro** [comment]
vcpkg in https://github.com/microsoft/vcpkg/pull/13264 basically replaced all the generation logic of assimp cmake config package with something more idiomatic go cmake, I did not checked it but it could be interesting.

**Comment by Tobias-Fischer** [comment]
Hmm, oddly enough `rviz` builds with the old version of assimp without those fixes in #8. Might have to revert them and wait for proper fixes (like the one on vcpkg @traversaro referred to) upstream. I think I couldn't build rviz in a catkin_ws without #8 but it seems to build fine directly on azure ...

Many thanks @traversaro!

**Pull request closed without merging**
